### ISSUE TITLE
Subsection of Analysis in Readme

### ISSUE THREAD

**Issue by odunbar** [maumlima/Rivers#3]
## Purpose

could we add a note about how to produce the tested outputs of the LSTM?

## Example solution

https://github.com/maumlima/Rivers/blob/9895f8cf545d9c6cf0331fc7ba435acbfa6bb6d7/examples/catchment_models/README.md?plain=1#L33

- Add a sentence to explain that `config.yml` contains the test data
- Explain that during training this file, along with training assessment is placed in a dynamically generated directory `run_dir`
- To evaluate the model one can follow the neuralhydrology command
```nh-run evaluate --run-dir /path/to/run_dir/```
with optional `--epoch N` to run with the LSTM at this epoch (e.g. one that minimizes a validation error)

**Comment by limamau** [comment]
Code updated with suggestions + simulate.py function to save metrics and simulations csv files.
