### ISSUE TITLE
Typo? in config for training

### ISSUE THREAD

**Issue by kmdeck** [maumlima/Rivers#5]
In the usa_time_split.yml, we have these lines:
https://github.com/maumlima/Rivers/blob/15b9cfbf1398128d5fec2773ca995dd5b7159e54/examples/catchment_models/neuralhydrology/usa_time_split.yml#L6-L17

We think it is correct that "path/to/basins.txt" is the same for training, validation, and test, but the train and test time windows should be different.

In the usa_basin_split.yml, it seems that now the paths are incorrect (they should point to a different file for testing, but the same one for training and validation?), while the time windows are correct: https://github.com/maumlima/Rivers/blob/15b9cfbf1398128d5fec2773ca995dd5b7159e54/examples/catchment_models/neuralhydrology/usa_basin_split.yml#L6-L17 (unless somehow this is also specifying to use a heldout 30% of basins)

**Comment by kmdeck** [comment]
@maumlima no need to correct soon, but we were wondering if the understanding is correct above

**Comment by limamau** [comment]
hey! yes times are wrong on `usa_time_split.yml`. The typo comes from the fact that I used a single configuration file but wrote these different files to make it easier for people to use/understand after.

the problem on the `usa_basin_split.yml` file was reported on https://github.com/maumlima/Rivers/issues/2. I'll modify it to make it clear, but you're right.

**Comment by limamau** [comment]
problem should be fixed in https://github.com/maumlima/Rivers/commit/0c48874968788e13424215c0d71a98617e12c374

**Comment by kmdeck** [comment]
thank you!
