### ISSUE TITLE
Incorrect column title

### ISSUE THREAD

**Issue by odunbar** [maumlima/Rivers#6]
## Issue
https://github.com/maumlima/Rivers/blob/1c3dd89ad1b1cb9c5b414749f1cff3f17cb33984/examples/catchment_models/benchmarks/get_benchmark_results.jl#L34
throws an error as there is no column titled `basin_id`

## solution 
Replace with 
```julia
base_df.basin
```

**Comment by limamau** [comment]
thanks for pointing that out! Corrected in: https://github.com/maumlima/Rivers/commit/80ba85bdeffa9ec4d39fe52ed8533e01bd2624f0
