### ISSUE TITLE
Overwriting leads to a necessary ordering in evaluation

### ISSUE THREAD

**Issue by odunbar** [maumlima/Rivers#7]
## Issue
to compute the channel output, the upstream integral is over just the hill-slope streamflows. However, as we compute channel flow, we are overwriting the hillslope data at that basin. This leads to `q_{HS} -> q_{HS} + q_{C}`. 

https://github.com/limamau/Rivers/blob/79d77024866b6b67fcecf74f82927c8e3180439a/src/routing/sub_processes/river_channel_routing.jl#L134

This is fine, but leads to a necessary (possibly counter-intuitive) ordering that one must update q at the most downstream basins first and then work in routing levels upstream. Are we following this convention with routing levels here? 

That is, do we start at the river mouth and finish at the root, when updating? It seems maybe we are doing the more intuitive (yet not correct) starting at the root and finish at the river mouth. Due to overwriting, this will likely lead to a large amount of overcounting of channel flow.
https://github.com/limamau/Rivers/blob/79d77024866b6b67fcecf74f82927c8e3180439a/src/routing/routing.jl#L153

## Possible solution
reverse the order of updating routing levels in the loop.

**Comment by limamau** [comment]
hey! I think I don't understand the issue yet... In this code we are following the routing levels in a crescent order (i.e., going from the source to the downstreams). At the outlet of a basin, the streamflow will be given as the sum of the hillslope routing of runoff inside it (what you are calling qHS) plus the streamflow at the outlet of each upstream summed and routed through the basin (maybe that's what you are calling qC?). Keep in mind that I only consider the channel routing of one basin to the next one, not from one basin to all downstreams. Let me know if that helps or if I haven't understood the problem :)

**Comment by odunbar** [comment]
Are you are using the mizuroute kernel? (e.g. eqns 8 & 9 from here: https://gmd.copernicus.org/articles/9/2223/2016/gmd-9-2223-2016.pdf)
to compute q^C in basin i, from what I can tell, this is an integral on _all_ upstream `q_{HS}` contributions (and _no_ `q_{C}` contributions upstream at all).  Following this pattern, you would need to compute these using all upstream `q_HS` each time

To convert it into a more graphical model (where you compute `q=q_{C}+q_{HS}` from neighbouring upstream `q`s ) then you would need to use a different formulation I think, because for example the kernel `h` is nonlinear in x.

**Comment by limamau** [comment]
maybe we should discuss some physics! but in (8) of the article you sent, U(t) can be either the hillslope from upstreams (which is what you are doing) or all the streamflow (so all parts summed) from upstreams. Both options are possible from my understanding, although I really prefer the last!

**Comment by odunbar** [comment]
Do you have some derivation of the latter one?

**Comment by limamau** [comment]
positive, sir! do you want me to send as a pdf? (it's hand written right now :p)

**Comment by odunbar** [comment]
Anything works for me! thanks - we are just trying to make sure that the ClimaRivers repository will be doing the same as your code, (or mizuroute v1) and currently this is a disconnect!
